# Generated by Django 6.0.2 on 2026-02-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('type', models.CharField(choices=[('PC', 'PC de Escritorio'), ('LAPTOP', 'Portátil'), ('AIO', 'All-in-One'), ('SERVER', 'Servidor'), ('PRINTER', 'Impresora'), ('SCANNER', 'Escáner'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='RAM')),
                ('storage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Almacenamiento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('MAINTENANCE', 'En Mantenimiento'), ('RETIRED', 'Dado de Baja'), ('aSTOCK', 'En Stock')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='inventory.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Realizado por')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('acta_pdf', models.FileField(blank=True, null=True, upload_to='maintenance_actas/', verbose_name='Acta PDF')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('type', models.CharField(choices=[('MONITOR', 'Monitor'), ('KEYBOARD', 'Teclado'), ('MOUSE', 'Mouse'), ('HEADSET', 'Diadema/Audífonos'), ('WEBCAM', 'Cámara Web'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FAULTY', 'Dañado'), ('RETIRED', 'Dado de Baja'), ('STOCK', 'En Stock')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripherals', to='inventory.area', verbose_name='Área')),
                ('connected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peripherals', to='inventory.equipment', verbose_name='Conectado a')),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('type', models.CharField(choices=[('ASSIGNMENT', 'Asignación'), ('RETURN', 'Devolución'), ('TRANSFER', 'Traslado')], max_length=20, verbose_name='Tipo de Entrega')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Recibido por')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('acta_pdf', models.FileField(blank=True, null=True, upload_to='handover_actas/', verbose_name='Acta de Entrega PDF')),
                ('destination_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_to', to='inventory.area', verbose_name='Área Destino')),
                ('equipment', models.ManyToManyField(blank=True, related_name='handovers', to='inventory.equipment', verbose_name='Equipos')),
                ('source_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_from', to='inventory.area', verbose_name='Área Origen')),
                ('peripherals', models.ManyToManyField(blank=True, related_name='handovers', to='inventory.peripheral', verbose_name='Periféricos')),
            ],
            options={
                'verbose_name': 'Entrega / Acta',
                'verbose_name_plural': 'Entregas / Actas',
            },
        ),
    ]
