# Generated by Django 6.0.2 on 2026-02-03 20:37

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0002_handover_technician_alter_maintenance_performed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Centro de Costos',
                'verbose_name_plural': 'Centros de Costos',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
            ],
            options={
                'verbose_name': 'Ingeniero / Técnico',
                'verbose_name_plural': 'Ingenieros / Técnicos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='handover',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre quien recibe (Opcional)'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('identification', models.CharField(max_length=20, unique=True, verbose_name='Identificación / Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Cliente / Funcionario',
                'verbose_name_plural': 'Clientes / Funcionarios',
            },
        ),
        migrations.AddField(
            model_name='handover',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client', verbose_name='Cliente / Funcionario'),
        ),
        migrations.AddField(
            model_name='area',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.costcenter', verbose_name='Centro de Costos'),
        ),
    ]
