# Generated by Django 6.0.2 on 2026-02-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_costcenter_technician_alter_handover_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='amperage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Amperaje'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='os_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario SO'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamaño Pantalla'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='voltage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voltaje'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cleaning_cco',
            field=models.BooleanField(default=False, verbose_name='Ejecución C-Cleaner'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cleaning_defrag',
            field=models.BooleanField(default=False, verbose_name='Desfragmentación Disco'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cleaning_scandisk',
            field=models.BooleanField(default=False, verbose_name='ScanDisk'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cleaning_space',
            field=models.BooleanField(default=False, verbose_name='Liberación Espacio'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_chassis',
            field=models.BooleanField(default=False, verbose_name='Limpieza Chasis/Cubiertas'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_contacts',
            field=models.BooleanField(default=False, verbose_name='Limpiador Contactos'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_disassembly',
            field=models.BooleanField(default=False, verbose_name='Retiro equipo / Desmontaje'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_fans',
            field=models.BooleanField(default=False, verbose_name='Limpieza Ventiladores'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_keyboard_mouse',
            field=models.BooleanField(default=False, verbose_name='Limpieza Teclado/Mouse'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_power_supply',
            field=models.BooleanField(default=False, verbose_name='Limpieza Fuente Poder'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_reassembly',
            field=models.BooleanField(default=False, verbose_name='Ensamble y Pruebas'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_screen',
            field=models.BooleanField(default=False, verbose_name='Limpieza Pantalla'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hw_thermal_paste',
            field=models.BooleanField(default=False, verbose_name='Crema Disipadora'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_backup',
            field=models.BooleanField(default=False, verbose_name='Copia Seguridad'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_cleaning',
            field=models.BooleanField(default=False, verbose_name='Limpieza Equipo'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_connection',
            field=models.BooleanField(default=False, verbose_name='Problemas Conexión'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_install',
            field=models.BooleanField(default=False, verbose_name='Instalación Software'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_peripheral',
            field=models.BooleanField(default=False, verbose_name='Falla Periféricos'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_review',
            field=models.BooleanField(default=False, verbose_name='Revisión Equipo'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_software_failure',
            field=models.BooleanField(default=False, verbose_name='Fallas Software'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_updates',
            field=models.BooleanField(default=False, verbose_name='Actualizaciones (Win10)'),
        ),
    ]
