# Generated by Django 6.0.2 on 2026-02-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ip_type',
            field=models.CharField(choices=[('DHCP', 'DHCP'), ('STATIC', 'Estática')], default='DHCP', max_length=20, verbose_name='Tipo de IP'),
        ),
    ]
