# Generated by Django 6.0.2 on 2026-02-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_equipment_ip_address_equipment_ip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='amperage',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='voltage',
        ),
    ]
