# Generated by Django 6.0.2 on 2026-02-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_equipment_amperage_remove_equipment_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='amperage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Amperaje (A)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='voltage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voltaje'),
        ),
    ]
