# Generated by Django 6.0.2 on 2026-02-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_equipment_amperage_equipment_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Realizado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'Cronograma de Mantenimiento',
                'verbose_name_plural': 'Cronogramas de Mantenimiento',
                'unique_together': {('equipment', 'scheduled_date')},
            },
        ),
    ]
