# Generated by Django 6.0.2 on 2026-02-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ownership_type',
            field=models.CharField(choices=[('OWNED', 'Propio (Institución)'), ('RENTED', 'Alquilado / Leasing')], default='OWNED', max_length=20, verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor / Empresa'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_contract_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref. Contrato / Ticket'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='support_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Soporte'),
        ),
    ]
