# Generated by Django 6.0.2 on 2026-02-12 02:20

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_equipment_ownership_type_equipment_provider_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='Número de Serie')),
                ('type', models.CharField(choices=[('PC', 'PC de Escritorio'), ('LAPTOP', 'Portátil'), ('AIO', 'All-in-One'), ('SERVER', 'Servidor'), ('PRINTER', 'Impresora'), ('SCANNER', 'Escáner'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='RAM')),
                ('storage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Almacenamiento')),
                ('os_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario SO')),
                ('screen_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamaño Pantalla')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('MAINTENANCE', 'En Mantenimiento'), ('RETIRED', 'Dado de Baja'), ('aSTOCK', 'En Stock')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('ip_type', models.CharField(choices=[('DHCP', 'DHCP'), ('STATIC', 'Estática')], default='DHCP', max_length=20, verbose_name='Tipo de IP')),
                ('voltage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Voltaje')),
                ('amperage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amperaje (A)')),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Propio (Institución)'), ('RENTED', 'Alquilado / Leasing')], default='OWNED', max_length=20, verbose_name='Propiedad')),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor / Empresa')),
                ('rental_contract_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref. Contrato / Ticket')),
                ('support_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Soporte')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.area', verbose_name='Área')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Equipo',
                'verbose_name_plural': 'historical Equipos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMaintenance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción del Trabajo')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('acta_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Acta PDF')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('type_review', models.BooleanField(default=False, verbose_name='Revisión Equipo')),
                ('type_software_failure', models.BooleanField(default=False, verbose_name='Fallas Software')),
                ('type_connection', models.BooleanField(default=False, verbose_name='Problemas Conexión')),
                ('type_updates', models.BooleanField(default=False, verbose_name='Actualizaciones (Win10)')),
                ('type_cleaning', models.BooleanField(default=False, verbose_name='Limpieza Equipo')),
                ('type_install', models.BooleanField(default=False, verbose_name='Instalación Software')),
                ('type_peripheral', models.BooleanField(default=False, verbose_name='Falla Periféricos')),
                ('type_backup', models.BooleanField(default=False, verbose_name='Copia Seguridad')),
                ('cleaning_defrag', models.BooleanField(default=False, verbose_name='Desfragmentación Disco')),
                ('cleaning_cco', models.BooleanField(default=False, verbose_name='Ejecución C-Cleaner')),
                ('cleaning_scandisk', models.BooleanField(default=False, verbose_name='ScanDisk')),
                ('cleaning_space', models.BooleanField(default=False, verbose_name='Liberación Espacio')),
                ('hw_disassembly', models.BooleanField(default=False, verbose_name='Retiro equipo / Desmontaje')),
                ('hw_power_supply', models.BooleanField(default=False, verbose_name='Limpieza Fuente Poder')),
                ('hw_fans', models.BooleanField(default=False, verbose_name='Limpieza Ventiladores')),
                ('hw_chassis', models.BooleanField(default=False, verbose_name='Limpieza Chasis/Cubiertas')),
                ('hw_thermal_paste', models.BooleanField(default=False, verbose_name='Crema Disipadora')),
                ('hw_contacts', models.BooleanField(default=False, verbose_name='Limpiador Contactos')),
                ('hw_keyboard_mouse', models.BooleanField(default=False, verbose_name='Limpieza Teclado/Mouse')),
                ('hw_screen', models.BooleanField(default=False, verbose_name='Limpieza Pantalla')),
                ('hw_reassembly', models.BooleanField(default=False, verbose_name='Ensamble y Pruebas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.equipment', verbose_name='Equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'historical Mantenimiento',
                'verbose_name_plural': 'historical Mantenimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
