# Generated by Django 6.0.2 on 2026-02-13 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_historicalequipment_historicalmaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeripheralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Periférico',
                'verbose_name_plural': 'Tipos de Periféricos',
            },
        ),
        migrations.AddField(
            model_name='peripheral',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad / Stock'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.CharField(blank=True, choices=[('MONITOR', 'Monitor'), ('KEYBOARD', 'Teclado'), ('MOUSE', 'Mouse'), ('HEADSET', 'Diadema/Audífonos'), ('WEBCAM', 'Cámara Web'), ('OTHER', 'Otro')], max_length=20, null=True, verbose_name='Tipo (Legacy)'),
        ),
        migrations.CreateModel(
            name='HandoverPeripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad Entregada')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.handover')),
                ('peripheral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.peripheral')),
            ],
        ),
        migrations.AddField(
            model_name='peripheral',
            name='peripheral_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.peripheraltype', verbose_name='Tipo'),
        ),
    ]
