# Generated by Django 6.0.2 on 2026-02-13 01:08

from django.db import migrations

def migrate_data(apps, schema_editor):
    Handover = apps.get_model('inventory', 'Handover')
    HandoverPeripheral = apps.get_model('inventory', 'HandoverPeripheral')
    
    # We need to access the auto-created through table for the existing M2M field.
    # The 'peripherals' field exists on Handover.
    # We can access the through model via the field's remote_field.through if available, or by name.
    # But with apps.get_model, we get a historical version.
    # The safest way might be to just assume the table name or use the field if it works.
    
    # Let's try iterating Handovers and accessing .peripherals.all()
    # Note: historical models might not have M2M descriptors fully working if the through table isn't explicitly defined in apps?
    # Actually, for standard M2M, it should work.
    
    for handover in Handover.objects.all():
        for peripheral in handover.peripherals.all():
            HandoverPeripheral.objects.get_or_create(
                handover=handover,
                peripheral=peripheral,
                defaults={'quantity': 1}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_populate_peripheral_types'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
