# Generated by Django 6.0.2 on 2026-02-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_migrate_m2m_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peripheral',
            name='type',
        ),
    ]
