# Generated by Django 6.0.2 on 2026-02-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_peripheral_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheral',
            old_name='peripheral_type',
            new_name='type',
        ),
    ]
