# Generated by Django 6.0.2 on 2026-02-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_peripheral_type_peripheral_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='peripherals',
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.peripheraltype', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
