# Generated by Django 6.0.2 on 2026-02-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_handover_peripherals_alter_peripheral_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='peripherals',
            field=models.ManyToManyField(blank=True, related_name='handovers', through='inventory.HandoverPeripheral', to='inventory.peripheral', verbose_name='Periféricos'),
        ),
    ]
