# Generated by Django 6.0.2 on 2026-02-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_handover_peripherals'),
    ]

    operations = [
        migrations.AddField(
            model_name='peripheral',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo (Alerta)'),
        ),
    ]
