# Generated by Django 6.0.2 on 2026-02-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_peripheral_min_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lifespan_years',
            field=models.PositiveIntegerField(default=5, verbose_name='Vida Útil (Años)'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='lifespan_years',
            field=models.PositiveIntegerField(default=5, verbose_name='Vida Útil (Años)'),
        ),
    ]
