# Generated by Django 6.0.2 on 2026-02-25 23:55

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_equipment_lifespan_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('powers_on', models.BooleanField(default=True, verbose_name='¿El equipo enciende correctamente?')),
                ('monitor_status', models.BooleanField(default=True, verbose_name='¿La pantalla/monitor funciona bien?')),
                ('peripherals_status', models.BooleanField(default=True, verbose_name='¿El mouse y teclado responden?')),
                ('network_status', models.BooleanField(default=True, verbose_name='¿Tiene conexión a la red/internet?')),
                ('os_status', models.BooleanField(default=True, verbose_name='¿El sistema operativo inicia sin errores?')),
                ('general_status', models.CharField(choices=[('GOOD', 'Bueno'), ('REGULAR', 'Regular'), ('BAD', 'Malo')], default='GOOD', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='inventory.equipment', verbose_name='Equipo')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
            ],
            options={
                'verbose_name': 'Ronda de Equipo',
                'verbose_name_plural': 'Rondas de Equipos',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipmentRound',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('powers_on', models.BooleanField(default=True, verbose_name='¿El equipo enciende correctamente?')),
                ('monitor_status', models.BooleanField(default=True, verbose_name='¿La pantalla/monitor funciona bien?')),
                ('peripherals_status', models.BooleanField(default=True, verbose_name='¿El mouse y teclado responden?')),
                ('network_status', models.BooleanField(default=True, verbose_name='¿Tiene conexión a la red/internet?')),
                ('os_status', models.BooleanField(default=True, verbose_name='¿El sistema operativo inicia sin errores?')),
                ('general_status', models.CharField(choices=[('GOOD', 'Bueno'), ('REGULAR', 'Regular'), ('BAD', 'Malo')], default='GOOD', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.equipment', verbose_name='Equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
            ],
            options={
                'verbose_name': 'historical Ronda de Equipo',
                'verbose_name_plural': 'historical Rondas de Equipos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
