# Generated by Django 6.0.2 on 2026-02-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_equipmentround_historicalequipmentround'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentround',
            name='cables_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Organización de Cables'),
        ),
        migrations.AddField(
            model_name='equipmentround',
            name='cleanliness_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Limpieza del Puesto'),
        ),
        migrations.AddField(
            model_name='equipmentround',
            name='hw_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Estado Físico / Chasis'),
        ),
        migrations.AddField(
            model_name='equipmentround',
            name='printer_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='NA', max_length=10, verbose_name='Impresora / Escáner'),
        ),
        migrations.AddField(
            model_name='equipmentround',
            name='ups_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='NA', max_length=10, verbose_name='Estado de UPS / Regulador'),
        ),
        migrations.AddField(
            model_name='historicalequipmentround',
            name='cables_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Organización de Cables'),
        ),
        migrations.AddField(
            model_name='historicalequipmentround',
            name='cleanliness_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Limpieza del Puesto'),
        ),
        migrations.AddField(
            model_name='historicalequipmentround',
            name='hw_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Estado Físico / Chasis'),
        ),
        migrations.AddField(
            model_name='historicalequipmentround',
            name='printer_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='NA', max_length=10, verbose_name='Impresora / Escáner'),
        ),
        migrations.AddField(
            model_name='historicalequipmentround',
            name='ups_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='NA', max_length=10, verbose_name='Estado de UPS / Regulador'),
        ),
        migrations.AlterField(
            model_name='equipmentround',
            name='monitor_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Pantalla / Monitor'),
        ),
        migrations.AlterField(
            model_name='equipmentround',
            name='network_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Conectividad / Red'),
        ),
        migrations.AlterField(
            model_name='equipmentround',
            name='os_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Sistema Operativo / Software'),
        ),
        migrations.AlterField(
            model_name='equipmentround',
            name='peripherals_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Teclado y Mouse'),
        ),
        migrations.AlterField(
            model_name='equipmentround',
            name='powers_on',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Encendido / Energía'),
        ),
        migrations.AlterField(
            model_name='historicalequipmentround',
            name='monitor_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Pantalla / Monitor'),
        ),
        migrations.AlterField(
            model_name='historicalequipmentround',
            name='network_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Conectividad / Red'),
        ),
        migrations.AlterField(
            model_name='historicalequipmentround',
            name='os_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Sistema Operativo / Software'),
        ),
        migrations.AlterField(
            model_name='historicalequipmentround',
            name='peripherals_status',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Teclado y Mouse'),
        ),
        migrations.AlterField(
            model_name='historicalequipmentround',
            name='powers_on',
            field=models.CharField(choices=[('PASS', '✅ Bien'), ('WARN', '⚠️ Regular'), ('FAIL', '❌ Malo'), ('NA', '➖ No Aplica')], default='PASS', max_length=10, verbose_name='Encendido / Energía'),
        ),
    ]
