# Generated by Django 6.0.2 on 2026-02-26 01:36

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_equipmentround_cables_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentround',
            options={'verbose_name': 'Ronda de Equipo', 'verbose_name_plural': 'Rondas de Equipos'},
        ),
        migrations.CreateModel(
            name='ComponentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('action_type', models.CharField(choices=[('ADDED', 'Agregado'), ('REMOVED', 'Retirado'), ('REPLACED', 'Reemplazado'), ('UPGRADED', 'Mejorado / Actualizado')], max_length=20, verbose_name='Tipo de Acción')),
                ('component_name', models.CharField(max_length=100, verbose_name='Pieza / Componente (Ej: RAM, Disco Duro)')),
                ('description', models.TextField(verbose_name='Descripción de los Cambios')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_logs', to='inventory.equipment', verbose_name='Equipo')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Cambio de Componente',
                'verbose_name_plural': 'Cambios de Componentes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalComponentLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('action_type', models.CharField(choices=[('ADDED', 'Agregado'), ('REMOVED', 'Retirado'), ('REPLACED', 'Reemplazado'), ('UPGRADED', 'Mejorado / Actualizado')], max_length=20, verbose_name='Tipo de Acción')),
                ('component_name', models.CharField(max_length=100, verbose_name='Pieza / Componente (Ej: RAM, Disco Duro)')),
                ('description', models.TextField(verbose_name='Descripción de los Cambios')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.equipment', verbose_name='Equipo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'historical Cambio de Componente',
                'verbose_name_plural': 'historical Cambios de Componentes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
