# Generated by Django 6.0.2 on 2026-02-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_equipmentround_options_componentlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentlog',
            name='peripheral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.peripheral', verbose_name='Pieza del Inventario (Opcional)'),
        ),
        migrations.AddField(
            model_name='componentlog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad (Stock a Deducir)'),
        ),
        migrations.AddField(
            model_name='historicalcomponentlog',
            name='peripheral',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.peripheral', verbose_name='Pieza del Inventario (Opcional)'),
        ),
        migrations.AddField(
            model_name='historicalcomponentlog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad (Stock a Deducir)'),
        ),
        migrations.AlterField(
            model_name='componentlog',
            name='component_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción de Pieza (Libre)'),
        ),
        migrations.AlterField(
            model_name='historicalcomponentlog',
            name='component_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción de Pieza (Libre)'),
        ),
    ]
