# Generated by Django 6.0.2 on 2026-02-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_componentlog_peripheral_componentlog_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tipo de Propiedad')),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedad',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ownership_type',
            field=models.CharField(choices=[('OWNED', 'Propio (Institución)'), ('RENTED', 'Alquilado / Leasing')], default='OWNED', max_length=20, verbose_name='Propiedad (Legacy)'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='ownership_type',
            field=models.CharField(choices=[('OWNED', 'Propio (Institución)'), ('RENTED', 'Alquilado / Leasing')], default='OWNED', max_length=20, verbose_name='Propiedad (Legacy)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='inventory.ownershiptype', verbose_name='Tipo de Propiedad'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='ownership',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.ownershiptype', verbose_name='Tipo de Propiedad'),
        ),
    ]
