# Generated by Django 6.0.2 on 2026-02-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_ownershiptype_alter_equipment_ownership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('MAINTENANCE', 'En Mantenimiento'), ('RETIRED', 'Dado de Baja'), ('STOCK', 'En Stock')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('MAINTENANCE', 'En Mantenimiento'), ('RETIRED', 'Dado de Baja'), ('STOCK', 'En Stock')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
    ]
