# Generated by Django 6.0.2 on 2026-02-26 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_ownershiptype_alter_equipment_ownership_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Explique el motivo por el cual el activo se da de baja (Ej. Daño irreparable, Obsolescencia).', verbose_name='Justificación de la Baja')),
                ('photo', models.ImageField(upload_to='retirement_evidence/%Y/%m/', verbose_name='Evidencia Fotográfica')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Baja')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retirement_logs', to='inventory.equipment', verbose_name='Equipo')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('peripheral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retirement_logs', to='inventory.peripheral', verbose_name='Periférico')),
            ],
            options={
                'verbose_name': 'Acta de Baja',
                'verbose_name_plural': 'Actas de Baja',
                'ordering': ['-date'],
            },
        ),
    ]
