# Generated by Django 6.0.2 on 2026-02-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_equipment_status_and_more'),
        ('inventory', '0026_retirementlog'),
    ]

    operations = [
    ]
