# Generated by Django 6.0.2 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_merge_20260225_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='HFPS TIC', max_length=100, verbose_name='Nombre del Sitio')),
                ('logo', models.ImageField(blank=True, help_text='Sube una imagen para cambiar el logo principal de la aplicación.', null=True, upload_to='site_logo/', verbose_name='Logo del Sistema')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
