# Generated by Django 6.0.2 on 2026-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='fixed_asset',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Activo Fijo'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='fixed_asset',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Activo Fijo'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='fixed_asset',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Activo Fijo'),
        ),
    ]
