# Generated by Django 6.0.2 on 2026-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_equipment_fixed_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_photos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto'),
        ),
    ]
