# Generated by Django 6.0.2 on 2026-03-10 16:20

from django.db import migrations
from django.core.management import call_command

def load_seed_data(apps, schema_editor):
    call_command('loaddata', 'seed_inventory.json')

def reverse_seed_data(apps, schema_editor):
    pass  # We usually don't want to auto-delete this structural data on unapply. 

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_client_signature_image_userprofile'),
    ]

    operations = [
        migrations.RunPython(load_seed_data, reverse_seed_data),
    ]
